# Generated by Django 6.0.4 on 2026-07-19 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='gst_rate',
            field=models.CharField(choices=[('0', '0%'), ('5', '5%'), ('12', '12%'), ('18', '18%'), ('28', '28%')], default='18', max_length=3),
        ),
    ]
